# names/email
email: "lianov@uab.edu"
multiqc_title: "scnanoseq_10X_3_prime"
#NOTE: for 3' data which is __V3__, default whitelist from pipeline is good to go

# input samplesheet
input: "./samplesheet.csv"

# Genome references
# genome use matching original BLAZE dataset publication
fasta: "/data/project/U_BDS/References/GENCODE/hg38/gencode_release_31/GRCh38.primary_assembly.genome.fa"
gtf: "/data/project/U_BDS/References/GENCODE/hg38/gencode_release_31/GTF/gencode.v31.annotation.gtf"

# other params
skip_trimming: false
skip_nanoplot: false
min_length: 500
min_q_score: 10

# fastq options
split_amount: 0 

# barcode options
barcode_format: "10X_3v3"
