# names/email
email: "lianov@uab.edu"
multiqc_title: "tumor_datasets_scnanoseq_oarfish"

# input samplesheet
input: "./samplesheet_full.csv"

# Genome references matching reported version in original publication
genome_fasta: "/data/project/U_BDS/References/GENCODE/hg38/gencode_release_32/GRCh38.primary_assembly.genome.fa"
transcript_fasta: "/data/project/U_BDS/References/GENCODE/hg38/gencode_release_32/gencode.v32.transcripts.fa.gz"
gtf: "/data/project/U_BDS/References/GENCODE/hg38/gencode_release_32/GTF/gencode.v32.annotation.gtf"

# other params
skip_trimming: false
skip_fastqc: false # since 1.1.0 not needed, but enabling for preprint
min_length: 500
min_q_score: 10

# quantification
quantifier: "isoquant,oarfish"

# fastq options
split_amount: 1000000

# barcode options
whitelist: "/scratch/lianov/FINAL_patch_1.1.0_tests/umitools_test_FINAL/stress_test/737K-arc-v1.txt"
barcode_format: "10X_3v3"

